### ISSUE TITLE
Update the readme (and create usage examples)

### ISSUE THREAD

**Issue by luismcosta** [feedzai/fairgbm#17]
## Summary
Update the readme  file

## Motivation
The project Readme is describing itself as LightGBM. It is understood that this is a consequence of the fork, but  should be updated.

**Comment by AndreFCruz** [comment]
Plus, create usage examples (notebooks and short code snippets in the Readme), and create sections for **Getting started**, **Contributing**, **Citing**, etc.

And leave a disclaimer stating that we diverged from Microsoft/LightGBM exactly at commit `fcd2453514a6ecd780121e4ea31a227559145451`
