### ISSUE TITLE
Major refactor of objective_function.h to split FairGBM and LightGBM logic

### ISSUE THREAD

**Issue by AlbertoEAF** [feedzai/fairgbm#2]
**EDIT**: unlike #9, this issue is focused on splitting the ObjectiveFunction and ConstrainedObjectiveFunction logic, so as to separate all of our FairGBM-induced changes to the codebase.

Issue #9 is more focused on optimization while this one is more focused on code maintainability.
___

The file `include/LightGBM/objective_function.h` must be heavily refactored.

First, the file should be split, so as to have a `constrained_objective_function.h` + `.cpp` file, and have a new `objective_functions.h` file that includes the original `objective_function.h`, as well as the new one. After that is done, the whole codebase should include `objective_functions.h` instead of the original one.

After that refactoring, there are plenty optimization opportunities in the `ConstrainedObjectiveFunction` class which will require extensive optimization, from making runtime code indirection cheaper, to re-implementing the code with cache-friendlier data structures, so as to reduce the +80% train time when compared to the vanilla LightGBM train.

**Comment by AndreFCruz** [comment]
Closed by #35
