### ISSUE TITLE
Training with validation set is not possible with the `fit` method of Python API

### ISSUE THREAD

**Issue by Scheggetta** [feedzai/fairgbm#48]
## Description
Is there a way to provide the validation set of the sensitive feature to the `fit` function of the Python class `FairGBMClassifier`? It does not seem so, or it is not documented. Does FairGBM even calculate validation scores for fairness metrics like equalized odds? This is also not documented.

Therefore, @NglQ and I delved deep into the source code of the aforementioned class. It turns out that there is a bug in the way the `eval_set` and `constraint_group` parameters interact when `eval_set` is provided. This issue occurs in the base class `LGBMModel` inside the `fit` method:

https://github.com/feedzai/fairgbm/blob/0bf83fdea192151c4013eb65e4e30cd41f58132d/python-package/fairgbm/sklearn.py#L865

The purpose of this line is to indeed create the validation set for the sensitive feature by using the **training set** of the sensitive feature (i.e., `constraint_group` variable) when the `eval_set` parameter is not `None` and contains correctly formatted data. Of course, this is generally incorrect for obvious reason, and it works only if the training set is equal to the validation set.

In one of your [notebook examples](https://github.com/feedzai/fairgbm/blob/main-fairgbm/examples/FairGBM-python-notebooks/FairGBM_example_for_equalized_odds_%5Bgoogle_colab%5D.ipynb), you use the python library [`hpt`](https://pypi.org/project/hyperparameter-tuning/) to provide a validation set to the same class `FairGBMClassifier`:
```python
obj_func = ObjectiveFunction(
    X_train=X_train, y_train=y_train, s_train=s_train,
    X_val=X_val, y_val=y_val, s_val=s_val,
    X_test=X_test, y_test=y_test, s_test=s_test,
    hyperparameter_space=fairgbm_hyperparam_space_path,
    eval_metric=PERF_METRIC,
    other_eval_metric=FAIR_METRIC,
    threshold=0.50,
)
```
So I assume this reported bug is only a problem when you provide the validation set directly to the `fit` method.

## Reproducible example
This is both a bug and a missing feature. The program allows you to provide a validation set for features and labels, but not for the sensitive feature:
```python
import numpy as np
from fairgbm import FairGBMClassifier

X_train = np.array([[1, 2], [3, 4]])
cg_train = [1, 3]
y_train = np.array([0, 1])
X_val = np.array([[5, 6], [7, 8]])
cg_val = [5, 7]
y_val = np.array([1, 0])

fairgbm_clf = FairGBMClassifier(
    constraint_type='FNR,FPR'
)

# Where should I put `cg_val`?
fairgbm_clf.fit(X_train, y_train, eval_set=[(X_val, y_val)], constraint_group=cg_train)
```

This code always throws the following error:
```
TypeError: Wrong type(int) for constraint_group.
It should be list, numpy 1-D array or pandas Series
```

## Environment info

FairGBM version or commit hash: 0.9.14

Command(s) you used to install FairGBM

```shell
pip install fairgbm
```

**Comment by AndreFCruz** [comment]
Thanks for the bug report!

The `hpt` package only uses the validation set to compute validation metrics, not to fit the fairness constraint. Currently the constraint can only fitted only on the training data, i.e., the same data is used to minimize the classification loss and to fit the constraint multipliers (to maximize the Lagrangian).

If what you were looking for was only a way to compute validation metrics and not to fit different parameters on different data sources, then I'd advise doing so outside of the `fit` function call. You can `fit` on training data and then evaluate on validation data by calling the `predict_proba`, just as the `hpt` package does.

**Comment by Scheggetta** [comment]
Thanks for your reply. I had guessed that since you could provide the `eval_set` to the `fit` function as in LightGBM, there was also the possibility to compute the validation metrics during training in order to allow early stopping.

Then, is `eval_set` a formal parameter present in the function signature just to be compatible with sklearn API?

**Comment by AndreFCruz** [comment]
The `eval_set` parameter is there to be passed on to the `LGBMModel` superclass. Then it falls back to lightgbm functions to handle it. This was not tested together with fairgbm, so there may very well be a bug in the way the lightgbm and fairgbm functionalities interact as you pointed out. Other key-word args such as `sample_weight` or `init_score` are also untested with fairgbm.

I'd advise sticking only to the `X, y, constraint_group` parameters for the `fit` method. Other parameters can work but you might have to change some code details.

**Comment by Scheggetta** [comment]
Ok, clear. I'm closing the issue.
